name: todo-to-pr-comment-issue example
on:
  pull_request:
  push:
    branches: [main]
permissions:
  issues: write
  pull-requests: write
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: stephansama/actions/todo-to-pr-comment-issue@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
