name: multi-deployments example
on:
  workflow_dispatch:
permissions:
  actions: read
  contents: write
  deployments: write
  id-token: write
  issues: write
  pull-requests: write
  statuses: write
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - name: Installing dependencies
        run: pnpm install
      - name: Build all actions
        run: pnpm run build
      - name: This is where you create your environments
        run: node ./scripts/generate-multi-urls.js
        id: generate
      - uses: stephansama/actions/multi-deployments@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          invalidate_previous: true
          environments: ${{steps.generate.outputs.environments}}
