name: do-not-track-polyfill example
on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion != 'success'}}
    steps:
      - uses: stephansama/actions/do-not-track-polyfill@v1
