name: multi-deployments
author: Stephan Randle
description: Create multiple deployments during one workflow
inputs:
  environments:
    description: Environments to deploy
    required: true
  invalidate_previous:
    default: "false"
    description: Invalidate previous deploys
    required: false
  ref:
    default: ""
    description: Commit ref to reference for deploys (automatically uses Github CI environments)
    required: false
runs:
  using: node20
  main: ./dist/index.js
