name: multi-deployments
description: Create multiple deployments during one workflow
inputs:
    envs:
        required: true
        description: Environments to deploy
    urls:
        required: true
        description: URLs to deploy matching envs
runs:
    using: node20
    main: "./dist/index.js"
