name: multi-deployments
author: Stephan Randle
description: Create multiple deployments during one workflow
inputs:
  environments:
    default: "{}"
    description: Environments to deploy
    required: true
  invalidate_previous:
    default: "false"
    description: Invalidate previous deploys
    required: false
  ref:
    default: ${{github.ref}}
    description: Commit ref to reference for deploys (automatically uses Github CI environments)
    required: false
  token:
    default: ${{github.token}}
    description: GitHub token used to create octokit client
    required: true
runs:
  using: node20
  main: ./dist/index.js
