name: multi-deployments
description: Create multiple deployments during one workflow
inputs:
  environments:
    required: true
    description: Environments to deploy
  invalidate_previous:
    required: true
    description: Invalidate previous deploys
runs:
  using: node20
  main: "./dist/index.js"
