name: multi-deployments
author: Stephan Randle
description: Create multiple deployments during one workflow
inputs:
  environments:
    required: true
    description: Environments to deploy
  invalidate_previous:
    required: false
    description: Invalidate previous deploys
    default: "false"
runs:
  using: node20
  main: ./dist/index.js
