name: coverage
on:
  push:
    branches: [main]
    paths:
      - do-not-track-polyfill/*
      - multi-deployments/*
  workflow_dispatch:
env:
  HUSKY: 0
permissions:
  actions: write
  contents: write
  id-token: write
  pull-requests: write
  statuses: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - name: 📦 Installing dependencies
        run: pnpm install
      - name: 🧪 Upload coverage reports to Codecov 🔼
        uses: codecov/codecov-action@v5
        with:
          disable_telem: true
      - name: 🧪 Upload test results to Codecov 🔼
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
