name: coverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "**.ts"
  workflow_dispatch:
env:
  HUSKY: 0
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: stephansama/actions/do-not-track-polyfill@v1
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - name: 📦 Installing dependencies
        run: pnpm install
      - name: 🧪 Create coverage reports
        run: pnpm run test:ci
      - name: 🧪 Upload coverage reports to Codecov 🔼
        uses: codecov/codecov-action@v5
        with:
          disable_telem: true
      - name: 🧪 Upload test results to Codecov 🔼
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
